[server]
runOnSave = true
fileWatcherType = "auto"

[runner]
fastReruns = false

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false

# Force cache clear - version 2
[global]
developmentMode = false
